# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.9
        environment:
          PIPENV_VENV_IN_PROJECT: true

    working_directory: ~/repo

    steps:
      - checkout
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - restore_cache:
          keys:
            - pipenv-packages-{{ checksum "continuous_integration/install_or_skip_dependencies.py" }}
            - pipenv-packages-
      - run:
          command: |
            python -m continuous_integration --install_or_skip_dependencies
      - save_cache:
          paths:
            - "Pipfile"
            - "Pipfile.lock"
          key: pipenv-packages-{{ checksum "continuous_integration/install_or_skip_dependencies.py" }}

      - run:
          name: run black - format checker
          command: |
            pipenv run python -m continuous_integration --black
      - run:
          name: run pylint - lint checker
          command: |
            pipenv run python -m continuous_integration --pylint
      - run:
          name: run code complexity check
          command: |
            pipenv run python -m continuous_integration --xenon
      - run:
          name: run mypy - static analysis checker
          command: |
            pipenv run python -m continuous_integration --mypy
      - run:
          name: run unit tests with coverage check
          command: |
            pipenv run python -m continuous_integration --tests
      - run:
          name: run code cov
          command: |
            pipenv run codecov
